version: '3.9'

services:
  backend:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
        - HOST_UID=${HOST_UID-1000}
    depends_on:
      database:
        condition: service_healthy
    entrypoint: /var/www/.docker/fpm/entrypoint.sh
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=${APP_ENV-dev}
      # PHP
      - PHP_OPCACHE=${PHP_OPCACHE-0}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG-client_host=172.17.0.1}
      - XDEBUG_ENABLED=${XDEBUG_ENABLED-true}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG-serverName=_}
      # Database
      - DATABASE_URL=${DATABASE_URL-pgsql://telegram:qwerty@database:5432/telegram?serverVersion=13&charset=utf8}

  nginx:
    image: "harbor.lab.movavi.com/common/nginx-movavi:1.20.2-alpine"
    links:
      - backend
    ports:
      - ${EXTERNAL_HTTP_PORT-80}:80
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"

  database:
    image: postgres:13-alpine
    ports:
      - "${EXTERNAL_DB_PORT-5433}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-telegram}
      - POSTGRES_DB=${POSTGRES_DB:-telegram}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}
    healthcheck:
      test: pg_isready -U telegram -d telegram
      interval: 3s
      timeout: 2s
      retries: 5


